version: '3.1'

services:
  otusdb:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=my_pass
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  data:
