version: '3.1'

services:
  otusdb:
    image: mysql:8.0.19
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - data:/var/lib/mysql
      - ./custom.conf.d:/etc/mysql/conf.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
